# Generated by Django 5.2.3 on 2026-04-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='emergency_note',
            field=models.CharField(blank=True, help_text='e.g. Available for emergency surgery only', max_length=255, null=True),
        ),
    ]
