# Generated by Django 6.0.4 on 2026-04-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_availability_emergency_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='emergency_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='emergency_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='emergency_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
