# Generated by Django 6.0.4 on 2026-04-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_availability_id_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='current_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='max_patients',
            field=models.PositiveIntegerField(default=1, help_text='How many patients can book this slot?'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
